---
- name: Ensure report directory exists
  ansible.windows.win_file:
    path: "C:\\Users\\p-sve7fz\\Desktop"
    state: directory

- name: Debug template selection
  ansible.builtin.debug:
    msg: "Using template: fullreport.j2"
  run_once: true

- name: Create HTML report
  ansible.windows.win_template:
    src: fullreport.j2
    dest: "C:\\Users\\p-sve7fz\\Desktop\\windows.html"
  run_once: true

- name: Copy CSS directory
  ansible.windows.win_copy:
    src: css
    dest: "C:\\Users\\p-sve7fz\\Desktop\\css"
    remote_src: no
    recurse: yes
  run_once: true

- name: Copy logos
  ansible.windows.win_copy:
    src: "{{ item }}"
    dest: "C:\\Users\\p-sve7fz\\Desktop\\{{ item }}"
    remote_src: no
  loop:
    - "webpage_logo.png"
    - "redhat-ansible-logo.svg"
    - "server.png"
  run_once: true

- name: Restart IIS to reload content
  ansible.windows.win_shell: iisreset
  args:
    warn: false
  run_once: true

- name: Display link to inventory report
  ansible.builtin.debug:
    msg: "Please go to http://{{ ansible_host }}/windows.html"
  run_once: true
