- name: Ensure report directory exists
  ansible.windows.win_file:
    path: "C:\\Users\\p-sve7fz\\Desktop"
    state: directory

- name: Collect required_updates from all hosts
  ansible.builtin.set_fact:
    required_updates_dict: >-
      {{
        required_updates_dict | default({}) | combine({
          inventory_hostname: hostvars[inventory_hostname].required_updates | default([])
        })
      }}

- name: Collect last_applied_patches from all hosts
  ansible.builtin.set_fact:
    last_applied_patches_dict: >-
      {{
        last_applied_patches_dict | default({}) | combine({
          inventory_hostname: hostvars[inventory_hostname].last_applied_patches | default([])
        })
      }}

- name: Debug selected template (forced to fullreport.j2)
  ansible.builtin.debug:
    msg: "Using template: fullreport.j2"

- name: Create HTML report using fullreport.j2
  ansible.windows.win_template:
    src: fullreport.j2
    dest: "C:\\Users\\p-sve7fz\\Desktop\\windows.html"
  vars:
    required_updates: "{{ required_updates_dict }}"
    last_applied_patches: "{{ last_applied_patches_dict }}"

- name: Copy CSS directory over
  ansible.windows.win_copy:
    src: css
    dest: "C:\\Users\\p-sve7fz\\Desktop\\css"
    remote_src: no
    recurse: yes

- name: Copy logos over
  ansible.windows.win_copy:
    src: "{{ item }}"
    dest: "C:\\Users\\p-sve7fz\\Desktop\\{{ item }}"
    remote_src: no
  loop:
    - "webpage_logo.png"
    - "redhat-ansible-logo.svg"
    - "server.png"

- name: Restart IIS to reload content
  ansible.windows.win_shell: iisreset
  args:
    warn: false

- name: Display link to inventory report
  ansible.builtin.debug:
    msg: "Please go to http://{{ ansible_host }}/windows.html"
