- name: Ensure report directory exists
  ansible.windows.win_file:
    path: "{{ file_path }}"
    state: directory

- name: Create HTML report if jinja include works
  ansible.windows.win_template:
    src: report.j2
    dest: "{{ file_path }}\\windows.html"
  when: usesingletemplate

- name: Create HTML report if jinja include doesn't work
  ansible.windows.win_template:
    src: fullreport.j2
    dest: "{{ file_path }}\\windows.html"
  when: usesingletemplate

- name: Copy CSS directory over
  ansible.windows.win_copy:
    src: css
    dest: "{{ file_path }}\\css"
    remote_src: no
    recurse: yes

- name: Copy logos over
  ansible.windows.win_copy:
    src: "{{ item }}"
    dest: "{{ file_path }}\\{{ item }}"
    remote_src: no
  loop:
    - "webpage_logo.png"
    - "redhat-ansible-logo.svg"
    - "server.png"

- name: Restart IIS to reload content
  ansible.windows.win_shell: iisreset
  args:
    warn: false

- name: Display link to inventory report
  ansible.builtin.debug:
    msg: "Please go to http://{{ ansible_host }}/windows.html"
