---
- name: "Scan packages (Windows)"
  shadowman.reports.win_scan_packages:
  when: ansible_os_family == "Windows"

- name: "Scan services (Windows)"
  shadowman.reports.win_scan_services:
  when: ansible_os_family == "Windows"

- name: Gather required Windows updates (Security and Critical)
  ansible.windows.win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
  register: required_updates
  when: ansible_os_family == "Windows"

- name: Gather last applied Windows patches (installed updates)
  ansible.windows.win_updates:
    state: installed
  register: last_applied_patches
  when: ansible_os_family == "Windows"

- name: Set required_updates fact
  set_fact:
    required_updates: "{{ required_updates.updates }}"
  when: ansible_os_family == "Windows"

- name: Set last_applied_patches fact
  set_fact:
    last_applied_patches: "{{ last_applied_patches.updates }}"
  when: ansible_os_family == "Windows"
