---
- name: Create Windows Report
  hosts: windows
  tasks:

    - name: Scan Systems for detailed report
      ansible.builtin.include_role:
        name: shadowman_scan_systems
      when: detailedreport == 'True'

    - name: Build the report
      ansible.builtin.include_role:
        name: build_report_windows
        apply:
          delegate_to: windows
          run_once: true
