---
- name: Create Windows Report
  hosts: windows
  tasks:

    - name: Scan Systems for detailed report
      include_role:
        name: shadowman_scan_systems
      when: detailedreport

    - name: Build the repor
      include_role:
        name: build_report_windows
