---
- name: Create Windows Report
  hosts: windows
  gather_facts: yes
  vars:
    detailedreport: True  # Set this to True to enable package/service scanning

  tasks:

    - name: Include system scanning role (collect updates, hotfixes, etc.)
      ansible.builtin.include_role:
        name: shadowman_scan_systems
      when: ansible_os_family == "Windows"

    - name: Build the HTML patch report
      ansible.builtin.include_role:
        name: build_report_windows
      run_once: true
