---
- name: Create Windows Report
  hosts: windows_servers
  gather_facts: yes
  vars:
    file_path: "C:\\inetpub\\wwwroot"

  tasks:
    - name: Scan Systems for detailed report
      include_role:
        name: shadowman_scan_systems
      when: detailedreport | default(false)

    - name: Build the report
      include_role:
        name: build_report_windows
